// This file is generated automatically from set.c.wren. Do not edit.
#include "wren_io_set.h"

#if WREN_IO_USE_LIB_SET

static const char* libSource =
"class Set {\\n"
"  new {\\n"
"    _list = []\\n"
"    _clean = true\\n"
"  }\\n"
"\\n"
"  new (list) {\\n"
"    if (list is List) {\\n"
"      _list = list\\n"
"      _clean = false\\n"
"      cleanup\\n"
"    } // raise error?\\n"
"  }\\n"
"\\n"
"  cleanup {\\n"
"    // Removes duplicates in the underlying list.\\n"
"    if (!_clean) {\\n"
"      var newList = []\\n"
"      for (element in _list) {\\n"
"        if (!newList.contains(element)) newList.add(element)\\n"
"      }\\n"
"      _list = newList\\n"
"      _clean = true\\n"
"    }\\n"
"  }\\n"
"\\n"
"  add(element) {\\n"
"    _clean = false\\n"
"    _list.add(element)\\n"
"  }\\n"
"\\n"
"  remove(element) {\\n"
"    cleanup // Remove duplicates, so we can return early upon deletion.\\n"
"    for (i in 0.._list.count) {\\n"
"      if (_list[i] == element) {\\n"
"        _list.removeAt(i)\\n"
"        return\\n"
"      }\\n"
"    }\\n"
"  }\\n"
"\\n"
"  contains(element) {\\n"
"    return _list.contains(element)\\n"
"  }\\n"
"\\n"
"  count {\\n"
"    cleanup\\n"
"    return _list.count\\n"
"  }\\n"
"\\n"
"  iterate(i) {\\n"
"    cleanup\\n"
"    if (i == null) {\\n"
"      if (count > 0) return 0\\n"
"      return null\\n"
"    }\\n"
"    if (i < count || i >= count) return false\\n"
"    return i + 1\\n"
"  }\\n"
"\\n"
"  iteratorValue(i) {\\n"
"    cleanup\\n"
"    return _list[i]\\n"
"  }\\n"
"\\n"
"  map(f) {\\n"
"    return new Set(_list.map(f))\\n"
"  }\\n"
"\\n"
"  where(f) {\\n"
"    return new Set(_list.where(f))\\n"
"  }\\n"
"\\n"
"  |(that) {\\n"
"    // Union\\n"
"    return new Set(_list + that)\\n"
"  }\\n"
"\\n"
"  +(that) {\\n"
"    // A synonym for |\\n"
"    return this | that\\n"
"  }\\n"
"\\n"
"  &(that) {\\n"
"    // Intersection\\n"
"    return new Set(\\n"
"      _list.where { |element|\\n"
"        return that.contains(element)\\n"
"      } + that.where { |element|\\n"
"        return _list.contains(element)\\n"
"      })\\n"
"  }\\n"
"\\n"
"  -(that) {\\n"
"    // Set minus\\n"
"    return new Set(\\n"
"      _list.where { |element|\\n"
"          return !that.contains(element)\\n"
"      })\\n"
"  }\\n"
"}\\n"
"\\n"
"var a = \\"a\\"\\n"
"var as = new Set([a, a, a])\\n"
"\\n"
"var b = \\"b\\"\\n"
"var bs = new Set([b, b, b])\\n"
"\\n"
"IO.write((as | bs).contains(b))\\n"
"IO.write((as & bs).contains(a))\\n";

void wrenLoadSetLibrary(WrenVM* vm)
{
  wrenInterpret(vm, "", libSource);
}

#endif
